name: "Submit a Feature Request"
title: (Enter title for this Discussion)
description: Tell the GitHub product team about your idea
labels: 
- "enhancement"
body:
- type: dropdown
  attributes:
    label: Will this feature, in its current release phase, flow into GitHub AE?
    description: This is controlled technically by whether the feature is still wrapped in a feature flag, has GHAE exclusion logic, or whether the flag is explicitly activated for GHAE. If so, select "Yes" and also pick the version label (if known). The GHES version will likely be the basis for the GHAE version. If the beta, for example, won't but the GA will, select "No" and also apply the `GHAE - NA` label to this issue.
    options:
      - "Actions"
      - "Yes - GHAE 3.2"
      - "Yes - GHAE 3.3"
      - "Yes - GHAE 3.4"
      - "Yes - GHAE 3.5"
      - "Yes - GHAE 3.6"
      - "Yes - GHAE version TBD"
  validations:
    required: true
    
- type: markdown
  attributes:
    value: |-
      Tell us about your feature request!

      Read our guide on How to 'Write a Great Feature Request'
