name: "Submit a Feature Request"
title: (Enter title for this Discussion)
description: Tell the GitHub product team about your idea
labels: 
- "enhancement"
body:
- type: dropdown
  attributes:
    options:
      - "Actions"
      - "Yes - GHAE 3.2"
      - "Yes - GHAE 3.3"
      - "Yes - GHAE 3.4"
      - "Yes - GHAE 3.5"
      - "Yes - GHAE 3.6"
      - "Yes - GHAE version TBD"
  validations:
    required: true
    
- type: markdown
  attributes:
    value: |-
      Tell us about your feature request!

      Read our guide on How to 'Write a Great Feature Request'
