name: "Submit a Feature Request"
title: (Enter title for this Discussion)
description: Tell the GitHub product team about your idea
labels: 
- "enhancement"
body:
- type: dropdown
  attributes:
    label: Select GitHub product
    description: Which area of GitHub do you want us to improve?
    options:
      - "🛳️ Actions & Packages"
      - "🛠️ APIs & Integations"
      - "🔎 Code Search"
      - "👩 Copilot"
      - "🤖 Dependabot"
      - "🎙️ Discussions"
      - "🐙 Issues"
      - "⭐ Lists"
      - "📱 Mobile"
      - "🖼️ Profile"
      - "✔️ Pull Requests"
      - "💖 Sponsors"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Short description of the project:"
    description: "Tell us about your feature request! Make sure to read our guide on [How to Write a Great Feature Request](https://www.google.com/)"
  validations:
    required: true
 
